# Generated by Django 5.2.7 on 2025-10-16 16:49

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider name (e.g., Vanguard, TD, RBC)', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('website', models.URLField(blank=True, help_text='Provider website URL')),
                ('description', models.TextField(blank=True, help_text='Brief description of the provider')),
                ('logo', models.ImageField(blank=True, help_text='Provider logo', null=True, upload_to='funds/providers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund Provider',
                'verbose_name_plural': 'Fund Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full fund name', max_length=255)),
                ('ticker', models.CharField(db_index=True, help_text='Ticker symbol (e.g., VFV, VGRO, TDB902)', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('fund_type', models.CharField(choices=[('MUTUAL_FUND', 'Mutual Fund'), ('ETF', 'Exchange-Traded Fund (ETF)')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, help_text='Fund description and investment strategy')),
                ('mer', models.DecimalField(decimal_places=2, help_text='Management Expense Ratio (MER) as percentage (e.g., 2.50 for 2.5%)', max_digits=5)),
                ('front_load', models.DecimalField(decimal_places=2, default=0.0, help_text='Front-end load fee as percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('back_load', models.DecimalField(decimal_places=2, default=0.0, help_text='Back-end load / DSC fee as percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee in dollars (e.g., 9.99)', max_digits=8)),
                ('asset_class', models.CharField(choices=[('EQUITY', 'Equity'), ('BONDS', 'Bonds / Fixed Income'), ('BALANCED', 'Balanced'), ('MONEY_MARKET', 'Money Market'), ('REAL_ESTATE', 'Real Estate / REITs'), ('COMMODITIES', 'Commodities'), ('ALTERNATIVE', 'Alternative')], db_index=True, max_length=20)),
                ('geographic_focus', models.CharField(choices=[('CANADIAN', 'Canadian'), ('US', 'United States'), ('INTERNATIONAL', 'International (Ex North America)'), ('GLOBAL', 'Global'), ('EMERGING', 'Emerging Markets'), ('REGIONAL', 'Regional / Specific Country')], db_index=True, max_length=20)),
                ('ytd_return', models.DecimalField(blank=True, decimal_places=2, help_text='Year-to-date return (%)', max_digits=6, null=True)),
                ('one_year_return', models.DecimalField(blank=True, decimal_places=2, help_text='1-year return (%)', max_digits=6, null=True)),
                ('three_year_return', models.DecimalField(blank=True, decimal_places=2, help_text='3-year annualized return (%)', max_digits=6, null=True)),
                ('five_year_return', models.DecimalField(blank=True, decimal_places=2, help_text='5-year annualized return (%)', max_digits=6, null=True)),
                ('ten_year_return', models.DecimalField(blank=True, decimal_places=2, help_text='10-year annualized return (%)', max_digits=6, null=True)),
                ('inception_date', models.DateField(blank=True, help_text='Date the fund was created', null=True)),
                ('aum', models.DecimalField(blank=True, decimal_places=2, help_text='Assets Under Management in millions (e.g., 1500.00 for $1.5B)', max_digits=15, null=True)),
                ('minimum_investment', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum investment amount in dollars', max_digits=10, null=True)),
                ('last_data_update', models.DateField(blank=True, help_text='Date when performance data was last updated', null=True)),
                ('data_source_url', models.URLField(blank=True, help_text="URL to fund's official page or data source")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the fund is still available for investment')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='feefifofunds.fundprovider')),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the NAV reading')),
                ('nav', models.DecimalField(decimal_places=4, help_text='Net Asset Value', max_digits=10)),
                ('daily_return', models.DecimalField(blank=True, decimal_places=2, help_text='Daily return percentage', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='feefifofunds.fund')),
            ],
            options={
                'verbose_name': 'Performance History',
                'verbose_name_plural': 'Performance Histories',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='fund',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='fund_search_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['fund_type', 'asset_class'], name='fund_type_class_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['mer'], name='fund_mer_idx'),
        ),
        migrations.AddIndex(
            model_name='performancehistory',
            index=models.Index(fields=['fund', '-date'], name='fund_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancehistory',
            unique_together={('fund', 'date')},
        ),
    ]
