# Generated by Django 5.2.7 on 2025-11-05 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('ticker', models.CharField(db_index=True, help_text='Primary ticker symbol or identifier', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Full asset name', max_length=255)),
                ('category', models.CharField(choices=[('STOCK', 'Stock/ETF'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity'), ('CURRENCY', 'Currency')], db_index=True, help_text='Asset category', max_length=20)),
                ('quote_currency', models.CharField(default='USD', help_text='Currency in which the asset is quoted (USD, EUR, BTC, etc.)', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the asset')),
                ('data_source', models.CharField(blank=True, help_text='Primary data source for this asset', max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this asset is actively tracked')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Date and time of this price record')),
                ('open', models.DecimalField(decimal_places=8, help_text='Opening price', max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, help_text='Highest price during period', max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, help_text='Lowest price during period', max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, help_text='Closing price', max_digits=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Trading volume (if applicable)', max_digits=20, null=True)),
                ('source', models.CharField(db_index=True, help_text="Data source for this price record (e.g., 'finnhub', 'massive', 'yahoo')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('asset', models.ForeignKey(help_text='Asset this price record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='feefifofunds.asset')),
            ],
            options={
                'verbose_name': 'Asset Price',
                'verbose_name_plural': 'Asset Prices',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp', 'source'], name='feefifofund_asset_i_dc1552_idx'), models.Index(fields=['asset', 'source'], name='feefifofund_asset_i_d5429f_idx'), models.Index(fields=['timestamp'], name='feefifofund_timesta_732fa9_idx'), models.Index(fields=['source'], name='feefifofund_source_42ef60_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'timestamp', 'source'), name='unique_asset_timestamp_source')],
            },
        ),
    ]
