# Generated by Django 5.2.7 on 2025-11-10 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(db_index=True, help_text='ID of the asset this price record belongs to')),
                ('time', models.DateTimeField(db_index=True, help_text='Date and time of this price record')),
                ('open', models.DecimalField(decimal_places=8, help_text='Opening price', max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, help_text='Highest price during period', max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, help_text='Lowest price during period', max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, help_text='Closing price', max_digits=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Trading volume (if applicable)', max_digits=20, null=True)),
                ('interval_minutes', models.SmallIntegerField(blank=True, db_index=True, help_text='Time interval in minutes (e.g., 1, 5, 15, 60, 1440 for daily). NULL for non-OHLCV data.', null=True)),
                ('trade_count', models.IntegerField(blank=True, help_text='Number of trades during this interval (for OHLCV data)', null=True)),
                ('quote_currency', models.CharField(db_index=True, default='USD', help_text='Currency in which the price is quoted (USD, EUR, BTC, etc.)', max_length=10)),
                ('source', models.CharField(db_index=True, help_text="Data source for this price record (e.g., 'finnhub', 'massive', 'kraken')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'verbose_name': 'Asset Price',
                'verbose_name_plural': 'Asset Prices',
                'db_table': 'assetprice',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(db_index=True, help_text='ID of the asset this trade belongs to')),
                ('time', models.DateTimeField(db_index=True, help_text='Exact time of the trade')),
                ('price', models.DecimalField(decimal_places=8, help_text='Trade execution price', max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, help_text='Trade volume/quantity', max_digits=20)),
                ('quote_currency', models.CharField(db_index=True, default='USD', help_text='Currency in which the price is quoted (USD, EUR, BTC, etc.)', max_length=10)),
                ('source', models.CharField(db_index=True, default='kraken', help_text="Data source for this trade (e.g., 'kraken')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trade',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('ticker', models.CharField(db_index=True, help_text='Primary ticker symbol or identifier', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Full asset name', max_length=255)),
                ('category', models.CharField(choices=[('STOCK', 'Stock/ETF'), ('CRYPTO', 'Cryptocurrency'), ('COMMODITY', 'Commodity'), ('CURRENCY', 'Currency')], db_index=True, help_text='Asset category', max_length=20)),
                ('tier', models.CharField(choices=[('TIER1', 'Tier 1 - Major/Blue-chip'), ('TIER2', 'Tier 2 - Mid-cap/Established'), ('TIER3', 'Tier 3 - Small-cap/Emerging'), ('TIER4', 'Tier 4 - Micro-cap/Speculative'), ('UNCLASSIFIED', 'Unclassified')], db_index=True, default='UNCLASSIFIED', help_text='Asset tier classification based on market cap/importance', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the asset')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this asset is actively tracked')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['ticker'],
            },
        ),
    ]
