# Generated by Django 5.2.7 on 2025-11-06 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feefifofunds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Exact time of the trade')),
                ('price', models.DecimalField(decimal_places=8, help_text='Trade execution price', max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, help_text='Trade volume/quantity', max_digits=20)),
                ('source', models.CharField(db_index=True, default='kraken', help_text="Data source for this trade (e.g., 'kraken')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assetprice',
            name='unique_asset_timestamp_source',
        ),
        migrations.RemoveIndex(
            model_name='assetprice',
            name='feefifofund_asset_i_dc1552_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetprice',
            name='feefifofund_asset_i_d5429f_idx',
        ),
        migrations.AddField(
            model_name='assetprice',
            name='interval_minutes',
            field=models.SmallIntegerField(blank=True, db_index=True, help_text='Time interval in minutes (e.g., 1, 5, 15, 60, 1440 for daily). NULL for non-OHLCV data.', null=True),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='trade_count',
            field=models.IntegerField(blank=True, help_text='Number of trades during this interval (for OHLCV data)', null=True),
        ),
        migrations.AlterField(
            model_name='assetprice',
            name='source',
            field=models.CharField(db_index=True, help_text="Data source for this price record (e.g., 'finnhub', 'massive', 'kraken')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['asset', 'timestamp', 'interval_minutes'], name='feefifofund_asset_i_b862eb_idx'),
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['asset', 'interval_minutes'], name='feefifofund_asset_i_48d942_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetprice',
            constraint=models.UniqueConstraint(fields=('asset', 'timestamp', 'source', 'interval_minutes'), name='unique_asset_timestamp_source_interval'),
        ),
        migrations.AddField(
            model_name='trade',
            name='asset',
            field=models.ForeignKey(help_text='Asset this trade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='feefifofunds.asset'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['asset', 'timestamp'], name='feefifofund_asset_i_542a46_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['timestamp'], name='feefifofund_timesta_6dc787_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['asset'], name='feefifofund_asset_i_b2d2eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('asset', 'timestamp', 'source'), name='unique_trade_asset_timestamp_source'),
        ),
    ]
