# Generated by Django 5.2.7 on 2025-11-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feefifofunds', '0002_enable_timescaledb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityperformance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cryptoperformance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currencyperformance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundperformance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inflationdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyvaluation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savingsratehistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
