# Generated by Django 5.2.7 on 2025-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feefifofunds', '0002_configure_timescaledb_compression'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tier',
            field=models.CharField(choices=[('TIER1', 'Tier 1 - Major/Blue-chip'), ('TIER2', 'Tier 2 - Mid-cap/Established'), ('TIER3', 'Tier 3 - Small-cap/Emerging'), ('TIER4', 'Tier 4 - Micro-cap/Speculative'), ('UNCLASSIFIED', 'Unclassified')], db_index=True, default='UNCLASSIFIED', help_text='Asset tier classification based on market cap/importance', max_length=20),
        ),
    ]
