# Generated by Django 5.2.7 on 2025-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feefifofunds', '0003_add_tier_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetprice',
            name='unique_asset_time_source_interval',
        ),
        migrations.RemoveConstraint(
            model_name='trade',
            name='unique_trade_asset_time_source',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='quote_currency',
        ),
        migrations.AddField(
            model_name='assetprice',
            name='quote_currency',
            field=models.CharField(db_index=True, default='USD', help_text='Currency in which the price is quoted (USD, EUR, BTC, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='quote_currency',
            field=models.CharField(db_index=True, default='USD', help_text='Currency in which the price is quoted (USD, EUR, BTC, etc.)', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='assetprice',
            constraint=models.UniqueConstraint(fields=('asset', 'time', 'source', 'interval_minutes', 'quote_currency'), name='unique_asset_time_source_interval_currency'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('asset', 'time', 'source', 'quote_currency'), name='unique_trade_asset_time_source_currency'),
        ),
    ]
