# Generated by Django 5.2.8 on 2025-11-24 15:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feefifofunds', '0003_create_questdb_assetprice_with_dedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(help_text='Asset tier (TIER1, TIER2, etc.)', max_length=20)),
                ('intervals', models.JSONField(help_text='List of interval minutes to ingest (e.g., [60, 1440])')),
                ('start_date', models.DateField(help_text='Ingestion start date')),
                ('end_date', models.DateField(help_text='Ingestion end date')),
                ('csv_source_dir', models.CharField(help_text='Directory containing CSV files', max_length=500)),
                ('api_backfill_enabled', models.BooleanField(default=True, help_text='Enable API backfilling for gaps')),
                ('auto_gap_fill', models.BooleanField(default=True, help_text='Automatically fill API-fillable gaps')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('assets_count', models.IntegerField(default=0, help_text='Number of assets to ingest')),
                ('total_files', models.IntegerField(default=0, help_text='Total CSV files to process')),
                ('files_ingested', models.IntegerField(default=0, help_text='CSV files successfully processed')),
                ('files_failed', models.IntegerField(default=0, help_text='CSV files that failed')),
                ('files_skipped', models.IntegerField(default=0, help_text='CSV files skipped (already ingested)')),
                ('records_ingested', models.BigIntegerField(default=0, help_text='Total OHLCV records ingested')),
                ('gaps_detected', models.IntegerField(default=0, help_text='Number of gaps detected')),
                ('gaps_filled', models.IntegerField(default=0, help_text='Number of gaps filled via API')),
                ('gaps_unfillable', models.IntegerField(default=0, help_text='Number of unfillable gaps (>720 candles)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feefifofunds_ingestion_job',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tier', 'status'], name='feefifofund_tier_ff7b4c_idx'), models.Index(fields=['started_at'], name='feefifofund_started_780df9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataCoverageRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('interval_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(help_text='First timestamp in coverage range')),
                ('end_date', models.DateTimeField(help_text='Last timestamp in coverage range')),
                ('source', models.CharField(choices=[('CSV', 'CSV File'), ('API', 'Kraken API'), ('MIXED', 'Mixed Sources')], default='CSV', max_length=20)),
                ('record_count', models.BigIntegerField(help_text='Number of candles in range', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_verified', models.DateTimeField(auto_now=True, help_text='Last time this range was verified in QuestDB')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_ranges', to='feefifofunds.asset')),
            ],
            options={
                'db_table': 'feefifofunds_data_coverage_range',
                'ordering': ['asset', 'interval_minutes', 'start_date'],
                'indexes': [models.Index(fields=['asset', 'interval_minutes', 'start_date'], name='feefifofund_asset_i_e7e6de_idx'), models.Index(fields=['asset', 'interval_minutes', 'end_date'], name='feefifofund_asset_i_591d8d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date')],
            },
        ),
        migrations.CreateModel(
            name='GapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('interval_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gap_start', models.DateTimeField(help_text='Start of gap (missing data)')),
                ('gap_end', models.DateTimeField(help_text='End of gap (missing data)')),
                ('missing_candles', models.IntegerField(help_text='Number of missing candles', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_api_fillable', models.BooleanField(default=False, help_text='Can this gap be filled via Kraken API (within 720-candle limit)?')),
                ('overflow_candles', models.IntegerField(default=0, help_text='How many candles beyond 720-candle API limit')),
                ('candles_from_today', models.IntegerField(default=0, help_text='Number of candles from gap_start to today')),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('BACKFILLING', 'Backfilling'), ('FILLED', 'Filled'), ('UNFILLABLE', 'Unfillable - Requires CSV'), ('FAILED', 'Failed')], db_index=True, default='DETECTED', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('backfill_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('required_csv_file', models.CharField(blank=True, help_text='Suggested CSV filename to download from Kraken', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='feefifofunds.asset')),
            ],
            options={
                'db_table': 'feefifofunds_gap_record',
                'ordering': ['asset', 'interval_minutes', 'gap_start'],
                'indexes': [models.Index(fields=['asset', 'interval_minutes', 'status'], name='feefifofund_asset_i_f5de2d_idx'), models.Index(fields=['status', 'is_api_fillable'], name='feefifofund_status_2186e7_idx'), models.Index(fields=['detected_at'], name='feefifofund_detecte_38ef08_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('gap_end__gt', models.F('gap_start'))), name='gap_end_after_gap_start')],
            },
        ),
        migrations.CreateModel(
            name='FileIngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('file_path', models.CharField(help_text='Absolute path to CSV file', max_length=500, unique=True)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size_bytes', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file contents (for duplicate detection)', max_length=64)),
                ('interval_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INGESTING', 'Ingesting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped - Already Ingested')], db_index=True, default='PENDING', max_length=20)),
                ('records_count', models.BigIntegerField(default=0, help_text='Number of OHLCV records in file')),
                ('date_range_start', models.DateTimeField(blank=True, help_text='Earliest timestamp in file', null=True)),
                ('date_range_end', models.DateTimeField(blank=True, help_text='Latest timestamp in file', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_records', to='feefifofunds.asset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_records', to='feefifofunds.ingestionjob')),
            ],
            options={
                'db_table': 'feefifofunds_file_ingestion_record',
                'ordering': ['job', 'file_name'],
                'indexes': [models.Index(fields=['job', 'status'], name='feefifofund_job_id_2ad7fd_idx'), models.Index(fields=['asset', 'interval_minutes'], name='feefifofund_asset_i_3b108c_idx'), models.Index(fields=['file_hash'], name='feefifofund_file_ha_86cfe0_idx')],
            },
        ),
    ]
