# Pre-commit.ci Configuration
#
# Automated hook updates and checks via https://pre-commit.ci
# Free for public repositories, runs on EVERY commit (PRs AND direct pushes)
#
# Benefits:
# - Auto-updates hook versions weekly
# - Runs hooks on every commit to any branch
# - Auto-fixes and commits changes when possible
# - Creates fix PRs for protected branches

# Auto-update hook versions daily
autoupdate_schedule: daily

# Auto-update commits target this branch
autoupdate_branch: ''  # Empty = default branch (main)

# Commit message for auto-updates
autoupdate_commit_msg: 'chore(pre-commit): auto-update hook versions'

# IMPORTANT: Run on ALL branches (including main)
# Empty list = no branches skipped = runs everywhere
# To skip specific branches, add them here: ['branch-name']
skip_branches: []

# Hook IDs to skip on pre-commit.ci (but still run locally)
# Useful for hooks that require local resources or are slow
skip: []

# Submodules to check out recursively
submodules: false

# Auto-fix PRs (creates fixup commits with formatting fixes)
autofix_prs: true

# Auto-fix commits use this message
autofix_commit_msg: 'style: auto-fixes from pre-commit.ci hooks'

# Behavior on protected branches (like main):
# - Pre-commit.ci will RUN the hooks
# - If fixes are needed, it will CREATE A PR with fixes
# - It cannot push directly to protected branches
# - You'll need to merge the fix PR

# Behavior on non-protected branches (like feature branches in PRs):
# - Pre-commit.ci will RUN the hooks
# - If fixes are needed, it will COMMIT directly to the branch
# - Auto-fixes are immediate and automatic
