# Generated by Django 5.0.9 on 2024-09-08 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_action_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='pretty_name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='repo',
        ),
    ]
