# Generated by Django 5.0.9 on 2024-09-08 23:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_remove_action_pretty_name_remove_action_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.AddField(
            model_name='action',
            name='private_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
