# Generated by Django 5.0.9 on 2024-09-08 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_remove_action_name_action_private_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='private_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
