# Generated by Django 5.0.9 on 2024-09-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_alter_action_private_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=7)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
            ],
            options={
                'indexes': [models.Index(fields=['action'], name='actions_act_action__56fb70_idx'), models.Index(fields=['action', 'created_at'], name='actions_act_action__7ab1fe_idx')],
            },
        ),
    ]
