# Generated by Django 5.0.9 on 2024-09-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actionstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionstatus',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
