# Generated by Django 5.0.9 on 2024-09-08 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_alter_actionstatus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='action',
            name='branch',
            field=models.TextField(default='main'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('owner', 'url', 'branch')},
        ),
    ]
