# Generated by Django 5.0.9 on 2024-09-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_alter_action_unique_together_action_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstatus',
            name='previous_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.actionstatus'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.actionstatus')),
            ],
        ),
    ]
