# Generated by Django 5.0.9 on 2024-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_actionstatus_previous_status_notification'),
        ('utils', '0002_notificationemail_notificationphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='notify_emails',
            field=models.ManyToManyField(blank=True, to='utils.notificationemail'),
        ),
        migrations.AddField(
            model_name='action',
            name='notify_phone_numbers',
            field=models.ManyToManyField(blank=True, to='utils.notificationphonenumber'),
        ),
    ]
