# Generated by Django 5.0.9 on 2024-09-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_action_notify_emails_action_notify_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.action'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.actionstatus'),
        ),
    ]
