# Generated by Django 5.0.9 on 2024-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_alter_notification_action_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('failure', 'Failure'), ('error', 'Error')], max_length=14, null=True),
        ),
    ]
