# Generated by Django 5.1.1 on 2024-09-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
