# Generated by Django 5.1.1 on 2024-09-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
