# Generated by Django 5.1.1 on 2024-09-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0014_action_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstatus',
            name='checker',
            field=models.CharField(choices=[('badge', 'Badge'), ('api', 'API')], default='badge', max_length=10),
        ),
    ]
