# Generated by Django 5.1.1 on 2024-09-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0016_action_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='interval',
            field=models.CharField(choices=[('5M', '5 Minutes'), ('3M', '3 Minutes'), ('1M', '1 Minute'), ('30S', '30 Seconds')], default='5M', max_length=10),
        ),
    ]
