# Generated by Django 5.1.1 on 2024-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0017_alter_action_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionstatus',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], max_length=7),
        ),
    ]
