# Generated by Django 5.1.1 on 2024-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0018_alter_actionstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstatus',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
