# Generated by Django 5.2.5 on 2025-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LighthouseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='URL that was audited', max_length=500)),
                ('performance_score', models.IntegerField(help_text='Performance score (0-100)')),
                ('accessibility_score', models.IntegerField(help_text='Accessibility score (0-100)')),
                ('best_practices_score', models.IntegerField(help_text='Best Practices score (0-100)')),
                ('seo_score', models.IntegerField(help_text='SEO score (0-100)')),
                ('pwa_score', models.IntegerField(help_text='PWA score (0-100)')),
                ('audit_date', models.DateTimeField(auto_now_add=True, help_text='When the audit was run')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional Lighthouse data')),
            ],
            options={
                'verbose_name': 'Lighthouse Audit',
                'verbose_name_plural': 'Lighthouse Audits',
                'ordering': ['-audit_date'],
                'indexes': [models.Index(fields=['-audit_date'], name='lighthouse__audit_d_bd66ca_idx'), models.Index(fields=['url', '-audit_date'], name='lighthouse__url_b63ac3_idx')],
            },
        ),
    ]
