# Generated by Django 5.2.5 on 2025-10-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lighthouseaudit',
            name='pwa_score',
        ),
    ]
