# Generated by Django 5.2.5 on 2025-08-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_photo_file_size_photo_height_photo_image_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, help_text='Aperture (e.g., "f/2.8")', max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_make',
            field=models.CharField(blank=True, help_text='Camera manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(blank=True, help_text='Camera model', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(blank=True, help_text='Date photo was taken', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_data',
            field=models.JSONField(blank=True, help_text='Full EXIF data as JSON', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, help_text='Focal length (e.g., "50mm")', max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='gps_altitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS altitude in meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.PositiveIntegerField(blank=True, help_text='ISO value', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens_model',
            field=models.CharField(blank=True, help_text='Lens model', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, help_text='Shutter speed (e.g., "1/250")', max_length=50),
        ),
    ]
