# Generated by Django 5.2.5 on 2025-08-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_add_exif_metadata_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoalbum',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PhotoAlbum',
        ),
    ]

