# Generated by Django 5.2.6 on 2025-10-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_remove_photoalbum_photos_delete_photo_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageVisit",
        ),
    ]
