# Generated by Django 5.2.5 on 2025-08-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the original file for exact duplicate detection', max_length=64),
        ),
        migrations.AddField(
            model_name='photo',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Perceptual hash for similar image detection', max_length=64),
        ),
    ]
