# Generated by Django 5.2.5 on 2025-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photoalbum_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='allow_downloads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
