# Generated by Django 5.2.5 on 2025-08-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0006_add_focal_point_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image_large",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="image_medium",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="image_small",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="image_thumbnail",
        ),
        migrations.AddField(
            model_name="photo",
            name="image_display",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/display/",
                verbose_name="Display Version (Smart Cropped)",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_optimized",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="photos/optimized/",
                verbose_name="Optimized Full Size",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="photos/original/", verbose_name="Original Full Resolution"),
        ),
    ]
