# Generated by Django 5.2.5 on 2025-08-26 17:35

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_simplify_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Zip file containing original quality photos', null=True, storage=config.storage_backends.PrivateMediaStorage(), upload_to='albums/zips/original/'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='zip_file_optimized',
            field=models.FileField(blank=True, help_text='Zip file containing optimized quality photos', null=True, storage=config.storage_backends.PrivateMediaStorage(), upload_to='albums/zips/optimized/'),
        ),
    ]
