# Generated by Django 5.2.9 on 2025-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_add_album_zip_and_featured_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='complete', help_text='Status of background image processing', max_length=20),
        ),
    ]
