# Generated by Django 5.2.9 on 2025-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_add_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='photos/preview/', verbose_name='Preview Version (Full Size, Highly Compressed)'),
        ),
    ]
