# Generated by Django 5.2.9 on 2025-12-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_add_image_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_display',
            new_name='image_gallery_cropped',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_gallery_cropped',
            field=models.ImageField(blank=True, null=True, upload_to='photos/gallery_cropped/', verbose_name='Gallery Version (Smart Cropped)'),
        ),
    ]
