# Generated by Django 5.2.9 on 2025-12-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_rename_image_display_to_gallery_cropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Status of background image processing', max_length=20),
        ),
    ]
