# Generated by Django 5.2.9 on 2025-12-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_alter_photo_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_optimized',
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='zip_file',
            field=models.FileField(blank=True, help_text='ZIP file containing original photos from this album', null=True, upload_to='albums/zips/'),
        ),
    ]
