# Generated by Django 5.2.9 on 2025-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_rename_image_gallery_cropped_to_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='saliency_map',
            field=models.ImageField(blank=True, help_text='Visualization of saliency detection algorithm for debugging smart crop', null=True, upload_to='photos/saliency/', verbose_name='Saliency Map (Debug Visualization)'),
        ),
    ]
