# Generated by Django 5.2.9 on 2025-12-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_add_saliency_map_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
