# Generated by Django 5.2.9 on 2025-12-21 02:45

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0021_add_photo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photos.models.photo_upload_to, verbose_name='Original Full Resolution'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to=photos.models.preview_upload_to, verbose_name='Preview Version (Full Size, Highly Compressed)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=photos.models.thumbnail_upload_to, verbose_name='Thumbnail Version (Smart Cropped)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='saliency_map',
            field=models.ImageField(blank=True, help_text='Visualization of saliency detection algorithm for debugging smart crop', null=True, upload_to=photos.models.saliency_upload_to, verbose_name='Saliency Map (Debug Visualization)'),
        ),
    ]
