# Generated by Django 5.2.9 on 2025-12-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_alter_photo_image_alter_photo_image_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='focal_point_override',
            field=models.BooleanField(default=False, help_text='When enabled, prevents automatic focal point detection from overwriting the current focal point values'),
        ),
    ]
