# Generated by Django 5.2.5 on 2025-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_knowledgegraphscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog_category',
            field=models.CharField(default='tech', help_text="Category of the blog post (e.g., 'tech', 'personal')", max_length=50),
        ),
    ]
