# Generated by Django 5.2.7 on 2025-10-15 00:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_enable_postgres_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('blog_post', 'Blog Post'), ('project', 'Project'), ('book', 'Book')], db_index=True, help_text='Type of content (blog_post, project, book)', max_length=20)),
                ('title', models.CharField(help_text='Content title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Content description/excerpt')),
                ('content', models.TextField(blank=True, help_text='Full content text for search')),
                ('category', models.CharField(blank=True, db_index=True, help_text='Category (for blog posts: tech, personal, projects, etc.)', max_length=100)),
                ('url', models.CharField(help_text='URL path to the content', max_length=500)),
                ('template_name', models.CharField(blank=True, db_index=True, help_text='Template name for blog posts', max_length=255)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Searchable Content',
                'verbose_name_plural': 'Searchable Content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'category'], name='blog_search_content_43c2d5_idx'), models.Index(fields=['template_name'], name='blog_search_templat_f9afbe_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_idx')],
            },
        ),
    ]
