# Generated by Django 5.2.7 on 2025-10-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_searchablecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchableContent',
        ),
    ]
