# Generated by Django 5.1.1 on 2024-09-19 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0009_create_http_status_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2000)),
                ('private_id', models.UUIDField(default=uuid.uuid4)),
                ('interval', models.CharField(choices=[('5M', '5 Minutes'), ('3M', '3 Minutes'), ('1M', '1 Minute'), ('30S', '30 Seconds')], default='5M', max_length=10)),
                ('check_ssl_errors', models.BooleanField(default=True)),
                ('check_ssl_expiration', models.BooleanField(default=True)),
                ('check_domain_expiration', models.BooleanField(default=True)),
                ('follow_redirects', models.BooleanField(default=True)),
                ('http_method', models.CharField(choices=[('HEAD', 'HEAD'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('digest', 'Digest')], default='none', max_length=10)),
                ('auth_username', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=255, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('send_body_as_json', models.BooleanField(default=False)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('notify_emails', models.ManyToManyField(blank=True, to='utils.notificationemail')),
                ('notify_phone_numbers', models.ManyToManyField(blank=True, to='utils.notificationphonenumber')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('up_status_codes', models.ManyToManyField(blank=True, to='utils.httpstatuscode')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.IntegerField()),
                ('check_start_time', models.DateTimeField()),
                ('check_end_time', models.DateTimeField()),
                ('duration_ms', models.FloatField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.endpoint')),
            ],
        ),
    ]
