# Generated by Django 5.1.1 on 2024-09-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='domain_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='ssl_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='ssl_valid',
            field=models.BooleanField(default=False),
        ),
    ]
