# Generated by Django 5.1.1 on 2024-09-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_endpointstatus_domain_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], default='failure', max_length=7),
            preserve_default=False,
        ),
    ]
