# Generated by Django 5.1.1 on 2024-09-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_endpointstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
