# Generated by Django 5.1.1 on 2024-09-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_endpointstatus_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='check_ssl_errors',
            new_name='check_ssl',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='check_ssl_expiration',
        ),
    ]
