# Generated by Django 5.1.1 on 2024-09-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_check_ssl_errors_endpoint_check_ssl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointstatus',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=7),
        ),
    ]
