# Generated by Django 5.1.1 on 2024-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_endpointstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointstatus',
            name='ssl_valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
