# Generated by Django 5.1.1 on 2024-09-20 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_endpointstatus_ssl_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='region',
            field=models.CharField(choices=[('ap-southeast-5', 'Asia Pacific (Malaysia)'), ('ca-west-1', 'Canada West (Calgary)'), ('il-central-1', 'Israel (Tel Aviv)'), ('ap-southeast-4', 'Asia Pacific (Melbourne)'), ('ap-south-2', 'Asia Pacific (Hyderabad)'), ('eu-south-2', 'Europe (Spain)'), ('eu-central-2', 'Europe (Zurich)'), ('me-central-1', 'Middle East (UAE)'), ('ap-southeast-3', 'Asia Pacific (Jakarta)'), ('ap-northeast-3', 'Asia Pacific (Osaka)'), ('eu-south-1', 'Europe (Milan)'), ('af-south-1', 'Africa (Cape Town)'), ('me-south-1', 'Middle East (Bahrain)'), ('ap-east-1', 'Asia Pacific (Hong Kong)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ca-central-1', 'Canada (Central)'), ('cn-north-1', 'China (Beijing)'), ('cn-northwest-1', 'China (Ningxia)'), ('eu-central-1', 'Europe (Frankfurt)'), ('eu-north-1', 'Europe (Stockholm)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)'), ('eu-west-3', 'Europe (Paris)'), ('sa-east-1', 'South America (Sao Paulo)'), ('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)')], default='us-east-1', max_length=255),
        ),
        migrations.CreateModel(
            name='EndpointStatusCheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.endpoint')),
            ],
        ),
    ]
