# Generated by Django 5.1.1 on 2024-09-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_endpoint_enabled_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointstatus',
            name='region',
        ),
        migrations.RemoveField(
            model_name='endpointstatuscheckrequest',
            name='region',
        ),
    ]
