# Generated by Django 5.1.1 on 2024-09-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_populate_lambda_regions'),
        ('web', '0012_remove_endpointstatus_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.lambdaregion'),
        ),
        migrations.AddField(
            model_name='endpointstatuscheckrequest',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.lambdaregion'),
        ),
    ]
