# Generated by Django 5.1.1 on 2024-09-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_endpointstatus_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endpointstatus',
            options={'verbose_name': 'Endpoint Status', 'verbose_name_plural': 'Endpoint Statuses'},
        ),
    ]
