# Generated by Django 5.1.1 on 2024-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_endpoint_request_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='request_timeout_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
