# Generated by Django 5.1.1 on 2024-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_endpoint_request_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatuscheckrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
