# Generated by Django 5.1.1 on 2024-09-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_endpointstatuscheckrequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatuscheckrequest',
            name='received_response',
            field=models.BooleanField(default=False),
        ),
    ]
