# Generated by Django 5.1.1 on 2024-10-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_notificationconfig_created_at_and_more'),
        ('web', '0018_endpointstatuscheckrequest_received_response'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='endpointstatus',
            index=models.Index(fields=['endpoint'], name='web_endpoin_endpoin_574ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointstatus',
            index=models.Index(fields=['endpoint', 'check_start_time'], name='web_endpoin_endpoin_0d9cd0_idx'),
        ),
    ]
