# Generated by Django 5.1.1 on 2024-10-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_notificationconfig_created_at_and_more'),
        ('web', '0019_endpointstatus_web_endpoin_endpoin_574ceb_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='endpointstatus',
            index=models.Index(fields=['endpoint', 'region'], name='web_endpoin_endpoin_61245e_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointstatus',
            index=models.Index(fields=['endpoint', 'region', 'check_start_time'], name='web_endpoin_endpoin_53dbe0_idx'),
        ),
    ]
