# Generated by Django 5.2.7 on 2025-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_migrate_searchable_content_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfingerprint',
            name='geo_data',
            field=models.JSONField(blank=True, help_text='Geographic location data for IP address (city, country, lat/lon, etc.)', null=True),
        ),
    ]
