# Generated by Django 5.2.7 on 2025-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_normalize_ip_address_geolocation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requestfingerprint',
            index=models.Index(fields=['ip_address', '-created_at'], name='utils_reque_ip_addr_948953_idx'),
        ),
    ]
