# Generated by Django 5.2.7 on 2025-10-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_normalize_ip_address_geolocation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requestfingerprint',
            new_name='utils_reque_ip_addr_948953_idx',
            old_name='utils_reque_ip_addr_b174aa_idx',
        ),
    ]
