# Generated by Django 5.2.9 on 2025-12-15 01:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_fix_index_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('provider', models.CharField(help_text='The provider used for the API call', max_length=255)),
                ('model', models.CharField(help_text='The model used for the API call', max_length=255)),
                ('prompt', models.TextField(help_text='The prompt sent to the LLM')),
                ('response', models.TextField(blank=True, help_text='The response from the LLM')),
            ],
            options={
                'verbose_name': 'LLM Usage',
                'verbose_name_plural': 'LLM Usage Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
