# Generated by Django 5.2.9 on 2025-12-15 17:02
"""
Fingerprint Normalization Schema Migration.

Prepares the database for fingerprint normalization by:
- Soft-deprecating legacy fingerprint fields (nullable)
- Introducing the Fingerprint model
- Adding a nullable fingerprint_obj FK for backfilling

Data migration is performed in 0013_migrate_request_fingerprints.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_llmusage'),
    ]

    operations = [
        # Step 1: Make old fingerprint fields nullable (prepare for deprecation)
        migrations.AlterField(
            model_name='requestfingerprint',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='[DEPRECATED] SHA256 fingerprint including IP - use fingerprint_obj instead', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requestfingerprint',
            name='fingerprint_no_ip',
            field=models.CharField(blank=True, db_index=True, help_text='[DEPRECATED] SHA256 fingerprint excluding IP - use fingerprint_obj instead', max_length=64, null=True),
        ),
        # Step 2: Create Fingerprint model
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_with_ip', models.CharField(db_index=True, help_text='SHA256 fingerprint including IP address', max_length=64)),
                ('hash_without_ip', models.CharField(db_index=True, help_text='SHA256 fingerprint excluding IP (for cross-IP tracking)', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('request_count', models.PositiveIntegerField(default=0, help_text='Cached count of requests with this fingerprint')),
            ],
            options={
                'verbose_name': 'Fingerprint',
                'verbose_name_plural': 'Fingerprints',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['hash_with_ip'], name='utils_finge_hash_wi_6d5db8_idx'), models.Index(fields=['hash_without_ip'], name='utils_finge_hash_wi_9c4a16_idx'), models.Index(fields=['-last_seen'], name='utils_finge_last_se_494b78_idx'), models.Index(fields=['-request_count'], name='utils_finge_request_781235_idx')],
                'constraints': [models.UniqueConstraint(fields=('hash_with_ip', 'hash_without_ip'), name='unique_fingerprint_hashes')],
            },
        ),
        # Step 3: Add nullable fingerprint_obj FK to RequestFingerprint
        migrations.AddField(
            model_name='requestfingerprint',
            name='fingerprint_obj',
            field=models.ForeignKey(blank=True, help_text='Normalized fingerprint reference (replaces fingerprint CharField fields)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='utils.fingerprint'),
        ),
    ]
