# Generated by Django 5.2.9 on 2025-12-15 17:02
"""
Fingerprint Creation Data Migration.

Creates unique Fingerprint records from existing RequestFingerprint hashes.
Linking to requests is handled in 0014_link_request_fingerprints.
"""

import time

from django.db import migrations
from django.db.models import Count, Max, Min


def migrate_fingerprints_forward(apps, schema_editor):
    """Create Fingerprint records for each unique legacy hash pair."""
    start_time = time.time()

    RequestFingerprint = apps.get_model("utils", "RequestFingerprint")
    Fingerprint = apps.get_model("utils", "Fingerprint")

    total_fingerprints = RequestFingerprint.objects.count()
    unique_fps = (
        RequestFingerprint.objects.filter(
            fingerprint__isnull=False,
            fingerprint_no_ip__isnull=False,
        )
        .values("fingerprint", "fingerprint_no_ip")
        .annotate(
            first_seen=Min("created_at"),
            last_seen=Max("created_at"),
            count=Count("id"),
        )
        .distinct()
    )

    unique_count = unique_fps.count()

    print(f"\n{'='*70}")
    print("Fingerprint Creation")
    print(f"{'='*70}")
    print(f"📊 Total RequestFingerprint records: {total_fingerprints}")
    print(f"🔑 Unique fingerprint pairs to create: {unique_count}")
    if unique_count > 0 and total_fingerprints > 0:
        reduction = ((total_fingerprints - unique_count) / total_fingerprints * 100)
        print(f"💾 Estimated storage reduction: {reduction:.1f}%")
    print(f"{'='*70}\n")

    if unique_count == 0:
        print("✅ No fingerprints to create")
        return

    fingerprint_objs = []
    processed = 0

    for fp in unique_fps.iterator():
        fingerprint_objs.append(
            Fingerprint(
                hash_with_ip=fp["fingerprint"],
                hash_without_ip=fp["fingerprint_no_ip"],
                first_seen=fp["first_seen"],
                last_seen=fp["last_seen"],
                request_count=fp["count"],
            )
        )
        processed += 1

        if processed % 100 == 0 or processed == unique_count:
            print(
                f"   Creating Fingerprint records: {processed}/{unique_count} ({processed/unique_count*100:.1f}%)"
            )

    Fingerprint.objects.bulk_create(
        fingerprint_objs, batch_size=500, ignore_conflicts=True
    )
    print(f"   ✅ Created {unique_count} Fingerprint records")

    elapsed_time = time.time() - start_time
    print(f"\n{'='*70}")
    print("✅ Fingerprint creation complete")
    print(f"{'='*70}")
    print(f"⏱️  Total time: {elapsed_time:.2f} seconds")
    if unique_count > 0:
        print(f"⚡ Average: {elapsed_time/unique_count*1000:.2f}ms per fingerprint")
    print(f"{'='*70}\n")


def migrate_fingerprints_backward(apps, schema_editor):
    """Remove Fingerprint records created from legacy hashes."""
    Fingerprint = apps.get_model("utils", "Fingerprint")
    deleted, _ = Fingerprint.objects.all().delete()
    print(f"\n✅ Removed {deleted} Fingerprint records\n")


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_alter_requestfingerprint_fingerprint_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_fingerprints_forward, reverse_code=migrate_fingerprints_backward
        ),
    ]
