# Generated by Django 5.2.9 on 2025-12-15 17:02
"""
Fingerprint Linking Data Migration.

Links RequestFingerprint rows to Fingerprint records, then makes the FK required.
"""

import time

import django.db.models.deletion
from django.db import migrations, models


BATCH_SIZE = 1000


def link_fingerprints_forward(apps, schema_editor):
    """Link RequestFingerprint rows to existing Fingerprint records."""
    start_time = time.time()

    RequestFingerprint = apps.get_model("utils", "RequestFingerprint")
    Fingerprint = apps.get_model("utils", "Fingerprint")

    # Build lookup dict: (hash_with_ip, hash_without_ip) -> fingerprint_id
    print("\n🔍 Building fingerprint lookup table...")
    fingerprint_lookup = {
        (fp.hash_with_ip, fp.hash_without_ip): fp.id
        for fp in Fingerprint.objects.all()
    }
    print(f"   ✅ Loaded {len(fingerprint_lookup)} Fingerprint records")

    # Count unlinked records
    unlinked_qs = RequestFingerprint.objects.filter(
        fingerprint_obj_id__isnull=True,
        fingerprint__isnull=False,
        fingerprint_no_ip__isnull=False,
    )
    total = unlinked_qs.count()

    print(f"\n{'='*70}")
    print("Fingerprint Linking")
    print(f"{'='*70}")
    print(f"📊 Unlinked RequestFingerprint records: {total}")
    print(f"{'='*70}\n")

    if total == 0:
        print("✅ No records to link\n")
        return

    linked_count = 0
    not_found_count = 0
    processed = 0

    print("🔗 Linking RequestFingerprints to Fingerprint records...")

    while True:
        # Fetch next batch of unlinked records
        batch = list(
            RequestFingerprint.objects.filter(
                fingerprint_obj_id__isnull=True,
                fingerprint__isnull=False,
                fingerprint_no_ip__isnull=False,
            )[:BATCH_SIZE]
        )

        if not batch:
            break

        to_update = []
        batch_not_found = 0

        for rf in batch:
            key = (rf.fingerprint, rf.fingerprint_no_ip)
            fp_id = fingerprint_lookup.get(key)
            if fp_id:
                rf.fingerprint_obj_id = fp_id
                to_update.append(rf)
            else:
                batch_not_found += 1

        if to_update:
            RequestFingerprint.objects.bulk_update(to_update, ["fingerprint_obj_id"])
            linked_count += len(to_update)

        not_found_count += batch_not_found
        processed += len(batch)

        # Progress display
        elapsed = time.time() - start_time
        rate = processed / elapsed if elapsed > 0 else 0
        remaining = (total - processed) / rate if rate > 0 else 0
        pct = (processed / total) * 100

        print(
            f"   Progress: {processed:,}/{total:,} ({pct:.1f}%) | "
            f"Linked: {linked_count:,} | "
            f"Rate: {rate:.0f}/s | "
            f"ETA: {remaining:.0f}s"
        )

    elapsed_time = time.time() - start_time

    print(f"\n{'='*70}")
    print("✅ Linking complete")
    print(f"{'='*70}")
    print(f"🔗 Linked: {linked_count:,} RequestFingerprint records")
    if not_found_count > 0:
        print(f"⚠️  Not found: {not_found_count:,} (no matching Fingerprint)")
    print(f"⏱️  Total time: {elapsed_time:.2f} seconds")
    if linked_count > 0:
        print(f"⚡ Average: {elapsed_time/linked_count*1000:.2f}ms per record")
    print(f"{'='*70}\n")


def link_fingerprints_backward(apps, schema_editor):
    """Clear fingerprint links; legacy fields remain."""
    RequestFingerprint = apps.get_model("utils", "RequestFingerprint")

    updated = RequestFingerprint.objects.filter(
        fingerprint_obj_id__isnull=False
    ).update(fingerprint_obj_id=None)

    print(f"\n✅ Cleared fingerprint_obj on {updated:,} RequestFingerprint records\n")


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_migrate_request_fingerprints'),
    ]

    operations = [
        migrations.RunPython(
            link_fingerprints_forward, reverse_code=link_fingerprints_backward
        ),
        migrations.AlterField(
            model_name='requestfingerprint',
            name='fingerprint_obj',
            field=models.ForeignKey(help_text='Normalized fingerprint reference (replaces fingerprint CharField fields)', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='utils.fingerprint'),
        ),
    ]
