# Generated by Django 5.2.9 on 2025-12-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_link_request_fingerprints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HTTPStatusCode',
        ),
    ]
