# Generated by Django 5.2.9 on 2025-12-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_delete_httpstatuscode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='requestfingerprint',
            name='utils_reque_created_0d6629_idx',
        ),
        migrations.RemoveField(
            model_name='requestfingerprint',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='requestfingerprint',
            name='fingerprint_no_ip',
        ),
        migrations.AlterField(
            model_name='requestfingerprint',
            name='fingerprint_obj',
            field=models.ForeignKey(help_text='Normalized fingerprint reference', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='utils.fingerprint'),
        ),
    ]
