# Generated by Django 5.2.9 on 2025-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_remove_deprecated_fingerprint_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fingerprint',
            name='unique_fingerprint_hashes',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='utils_finge_hash_wi_6d5db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='utils_finge_hash_wi_9c4a16_idx',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='utils_finge_last_se_494b78_idx',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='utils_finge_request_781235_idx',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='hash_with_ip',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='request_count',
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='hash_without_ip',
            field=models.CharField(help_text='SHA256 fingerprint excluding IP (for cross-IP tracking)', max_length=64),
        ),
    ]
