# Generated by Django 5.2.9 on 2025-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_remove_fingerprint_unique_fingerprint_hashes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['hash_without_ip'], name='utils_finge_hash_wi_9c4a16_idx'),
        ),
    ]
