# Generated by Django 5.2.9 on 2025-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_fingerprint_utils_finge_hash_wi_9c4a16_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='utils_finge_hash_wi_9c4a16_idx',
        ),
        migrations.RenameField(
            model_name='fingerprint',
            old_name='hash_without_ip',
            new_name='hash',
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['hash'], name='utils_finge_hash_a8061b_idx'),
        ),
    ]
