# Generated by Django 5.2.9 on 2025-12-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_consolidate_duplicate_fingerprints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='hash',
            field=models.CharField(help_text='SHA256 fingerprint excluding IP (for cross-IP tracking)', max_length=64, unique=True),
        ),
    ]
