# Generated by Django 5.2.9 on 2025-12-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0021_alter_fingerprint_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename the model (preserves data)
        migrations.RenameModel(
            old_name="RequestFingerprint",
            new_name="TrackedRequest",
        ),
        # Update verbose_name and verbose_name_plural in Meta
        migrations.AlterModelOptions(
            name="trackedrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Tracked Request",
                "verbose_name_plural": "Tracked Requests",
            },
        ),
        # Update the related_name on fingerprint_obj ForeignKey
        migrations.AlterField(
            model_name="trackedrequest",
            name="fingerprint_obj",
            field=models.ForeignKey(
                help_text="Normalized fingerprint reference",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracked_requests",
                to="utils.fingerprint",
            ),
        ),
        # Update the related_name on ip_address ForeignKey
        migrations.AlterField(
            model_name="trackedrequest",
            name="ip_address",
            field=models.ForeignKey(
                help_text="IP address (with shared geolocation data)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracked_requests",
                to="utils.ipaddress",
            ),
        ),
        # Update the related_name on user ForeignKey
        migrations.AlterField(
            model_name="trackedrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracked_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
