# Generated by Django 5.2.9 on 2025-12-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_trackedrequest_delete_requestfingerprint_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trackedrequest',
            new_name='utils_track_ip_addr_729fa3_idx',
            old_name='utils_reque_ip_addr_948953_idx',
        ),
        migrations.RenameIndex(
            model_name='trackedrequest',
            new_name='utils_track_is_susp_f5aebf_idx',
            old_name='utils_reque_is_susp_db83b2_idx',
        ),
    ]
