# Generated by Django 5.2.9 on 2025-12-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_rename_utils_reque_ip_addr_948953_idx_utils_track_ip_addr_729fa3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='query_params',
            field=models.JSONField(blank=True, default=dict, help_text='Query string parameters'),
        ),
    ]
