# Generated by Django 5.2.9 on 2025-12-15 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0024_add_query_params_to_trackedrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='referer',
            field=models.TextField(blank=True, help_text='HTTP Referer header'),
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_pattern', models.CharField(blank=True, help_text='Regex pattern to match against user agent strings', max_length=500)),
                ('reason', models.TextField(help_text='Reason for the ban')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When the ban expires (null = permanent)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bans', to=settings.AUTH_USER_MODEL)),
                ('fingerprint', models.ForeignKey(blank=True, help_text='Ban a specific browser fingerprint (blocks across IP changes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='utils.fingerprint')),
                ('ip_address', models.ForeignKey(blank=True, help_text='Ban a specific IP address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='utils.ipaddress')),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Bans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='utils_ban_is_acti_7af5ff_idx')],
            },
        ),
    ]
