# Generated by Django 5.0.9 on 2024-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('template', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('parameters', models.TextField(blank=True, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('text_body', models.TextField(blank=True, null=True)),
                ('html_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
