# Generated by Django 5.0.9 on 2024-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_notificationemail_notificationphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationemail',
            name='verification_code_small',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
