# Generated by Django 5.0.9 on 2024-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_notificationemail_verification_code_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='template',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
