# Generated by Django 5.1.1 on 2024-09-13 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0013_delete_notification'),
        ('utils', '0004_textmessage_parameters_textmessage_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('failure', 'Failure'), ('error', 'Error')], max_length=14, null=True)),
                ('message', models.TextField()),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.actionstatus')),
            ],
        ),
    ]
