# Generated by Django 5.1.1 on 2024-09-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('failure', 'Failure'), ('success', 'Success')], max_length=14, null=True),
        ),
    ]
