# Generated by Django 5.1.1 on 2024-09-15 00:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationemail',
            name='unsubscribe_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
