# Generated by Django 5.1.1 on 2024-09-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_notificationemail_unsubscribe_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPStatusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
