# Generated by Django 5.1.1 on 2024-09-20 16:19

from django.db import migrations


def populate_lambda_regions(apps, schema_editor):
    LambdaRegion = apps.get_model('utils', 'LambdaRegion')
    regions = [
        ('us-east-1', 'US East (N. Virginia)'),
        ('us-east-2', 'US East (Ohio)'),
        ('us-west-1', 'US West (N. California)'),
        ('us-west-2', 'US West (Oregon)'),
        ('ap-south-1', 'Asia Pacific (Mumbai)'),
        ('ap-northeast-3', 'Asia Pacific (Osaka)'),
        ('ap-northeast-2', 'Asia Pacific (Seoul)'),
        ('ap-southeast-1', 'Asia Pacific (Singapore)'),
        ('ap-southeast-2', 'Asia Pacific (Sydney)'),
        ('ap-northeast-1', 'Asia Pacific (Tokyo)'),
        ('ca-central-1', 'Canada (Central)'),
        ('eu-central-1', 'Europe (Frankfurt)'),
        ('eu-west-1', 'Europe (Ireland)'),
        ('eu-west-2', 'Europe (London)'),
        ('eu-west-3', 'Europe (Paris)'),
        ('eu-north-1', 'Europe (Stockholm)'),
        ('sa-east-1', 'South America (São Paulo)'),
        ('af-south-1', 'Africa (Cape Town)'),
        ('ap-east-1', 'Asia Pacific (Hong Kong)'),
        ('ap-south-2', 'Asia Pacific (Hyderabad)'),
        ('ap-southeast-3', 'Asia Pacific (Jakarta)'),
        ('ap-southeast-5', 'Asia Pacific (Malaysia)'),
        ('ap-southeast-4', 'Asia Pacific (Melbourne)'),
        ('ca-west-1', 'Canada (Calgary)'),
        ('eu-south-1', 'Europe (Milan)'),
        ('eu-south-2', 'Europe (Spain)'),
        ('eu-central-2', 'Europe (Zurich)'),
        ('me-central-1', 'Middle East (UAE)'),
    ]
    for code, name in regions:
        LambdaRegion.objects.create(code=code, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_lambdaregion'),
    ]

    operations = [
        migrations.RunPython(populate_lambda_regions),
    ]
