# Generated by Django 5.1.1 on 2024-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_populate_lambda_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambdaregion',
            name='flag_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
