# Generated by Django 5.1.1 on 2024-09-20 16:37

from django.db import migrations

def populate_flag_codes(apps, schema_editor):
    LambdaRegion = apps.get_model('utils', 'LambdaRegion')
    flag_code_mapping = {
        'us-east-1': 'us',
        'us-east-2': 'us',
        'us-west-1': 'us',
        'us-west-2': 'us',
        'ca-central-1': 'ca',
        'eu-west-1': 'ie',
        'eu-central-1': 'de',
        'eu-west-2': 'gb',
        'eu-west-3': 'fr',
        'eu-north-1': 'se',
        'ap-northeast-1': 'jp',
        'ap-northeast-2': 'kr',
        'ap-southeast-1': 'sg',
        'ap-southeast-2': 'au',
        'ap-south-1': 'in',
        'sa-east-1': 'br',
    }
    
    for region in LambdaRegion.objects.all():
        region.flag_code = flag_code_mapping.get(region.code, '')
        region.save()

class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_lambdaregion_flag_code'),
    ]

    operations = [
        migrations.RunPython(populate_flag_codes),
    ]
