# Generated by Django 5.1.1 on 2024-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_populate_flag_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambdaregion',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
