# Generated by Django 5.1.1 on 2024-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_lambdaregion_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpstatuscode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lambdaregion',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
