# Generated by Django 5.1.1 on 2024-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_alter_httpstatuscode_code_alter_lambdaregion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lambdaregion',
            name='code_prefix',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
