# Generated by Django 5.1.1 on 2024-10-13 15:59

from django.db import migrations


def populate_code_prefix(apps, schema_editor):
    LambdaRegion = apps.get_model('utils', 'LambdaRegion')
    for region in LambdaRegion.objects.all():
        region.code_prefix = region.code[:2].upper()
        region.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_lambdaregion_code_prefix'),
    ]

    operations = [
        migrations.RunPython(populate_code_prefix),
    ]
