# Generated by Django 5.1.1 on 2024-10-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_populate_lambdaregion_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='status',
            new_name='action_status',
        ),
    ]
