# Generated by Django 5.1.1 on 2024-10-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_rename_status_notification_action_status'),
        ('web', '0018_endpointstatuscheckrequest_received_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.endpoint'),
        ),
        migrations.AddField(
            model_name='notification',
            name='endpoint_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.endpointstatus'),
        ),
    ]
