# Generated by Django 5.1.1 on 2024-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_notification_endpoint_notification_endpoint_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_enabled', models.BooleanField(default=True)),
                ('text_messages_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
