# Generated by Django 5.1.1 on 2024-10-17 15:36

from django.db import migrations
from django.db.models import Count

def create_notification_config(apps, schema_editor):
    NotificationConfig = apps.get_model('utils', 'NotificationConfig')
    if NotificationConfig.objects.count() == 0:
        NotificationConfig.objects.create(emails_enabled=True, text_messages_enabled=True)

class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_notificationconfig'),
    ]

    operations = [
        migrations.RunPython(create_notification_config),
    ]
