# Generated by Django 5.1.1 on 2024-10-17 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_create_notificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='emails_enabled',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='text_messages_enabled',
            field=models.BooleanField(),
        ),
    ]
