name: Test Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel previous runs for the same PR
concurrency:
  group: dependabot-test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

# Minimal permissions - read-only
permissions:
  contents: read

jobs:
  # Run tests for Dependabot PRs
  test-dependabot:
    # Only run on Dependabot PRs and skip if [skip ci] is in the title
    if: |
      github.actor == 'dependabot[bot]' &&
      !contains(github.event.pull_request.title, '[skip ci]')
    uses: ./.github/workflows/test-and-check.yml
    permissions:
      contents: read
    with:
      python-version: '3.12.2'
      upload-coverage: false  # Don't upload coverage for Dependabot PRs
      # Use the default ref - pull_request event automatically uses the PR merge commit
      # This is safe because pull_request runs with read-only permissions
