name: Test and Deploy

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test-and-check:
    uses: ./.github/workflows/test-and-check.yml
    with:
      python-version: '3.12.2'
      postgres-version: '15'
      upload-coverage: true
    secrets:
      DATABASE_URL: ${{secrets.DATABASE_URL}}

  deploy-caprover:
    runs-on: ubuntu-latest
    needs: test-and-check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            .
          outPath: deploy.tar
      - name: Deploy web app
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.NEW_CAPROVER_SERVER }}'
          app: '${{ secrets.CAPROVER_WEB_APP_NAME }}'
          token: '${{ secrets.NEW_CAPROVER_WEB_APP_TOKEN }}'