name: Test and Deploy

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

# Cancel in-progress runs for PRs but not for main branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-and-check:
    uses: ./.github/workflows/test-and-check.yml
    with:
      python-version: '3.12.2'
      postgres-version: '15'
      upload-coverage: true
    secrets:
      DATABASE_URL: ${{secrets.DATABASE_URL}}

  deploy-caprover:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test-and-check
    environment:
      name: production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create deployment archive
        run: |
          tar -czf /tmp/deploy.tar \
            --exclude='.git' \
            --exclude='*.pyc' \
            --exclude='__pycache__' \
            --exclude='venv' \
            --exclude='.env' \
            --exclude='staticfiles' \
            --exclude='media' \
            --exclude='.github' \
            --exclude='*.log' \
            --exclude='.DS_Store' \
            --exclude='deploy.tar' \
            .
          mv /tmp/deploy.tar deploy.tar
      - name: Deploy web app
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.CAPROVER_WEB_APP_NAME }}'
          token: '${{ secrets.CAPROVER_WEB_APP_TOKEN }}'
      - name: Deploy celery
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.CAPROVER_CELERY_APP_NAME }}'
          token: '${{ secrets.CAPROVER_CELERY_APP_TOKEN }}'
      - name: Deploy celerybeat
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.CAPROVER_CELERYBEAT_APP_NAME }}'
          token: '${{ secrets.CAPROVER_CELERYBEAT_APP_TOKEN }}'
      - name: Deploy flower
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.CAPROVER_FLOWER_APP_NAME }}'
          token: '${{ secrets.CAPROVER_FLOWER_APP_TOKEN }}'