# Generated by Django 5.0.9 on 2024-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interesteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
