# Generated by Django 5.0.9 on 2024-09-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notificationemail_notificationphonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationphonenumber',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationEmail',
        ),
        migrations.DeleteModel(
            name='NotificationPhoneNumber',
        ),
    ]
