# Generated by Django 5.1.1 on 2024-09-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_notificationphonenumber_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestedUser',
        ),
    ]
