# Generated by Django 5.1.1 on 2024-09-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_interesteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='paid_until',
        ),
    ]
